app: flex-fss-proxy
namespace: flex
team: flex
azureTenant: trygdeetaten.no
environment: dev
ingress: https://flex-fss-proxy.dev-fss-pub.nais.io
env:
  KODEVERK_URL: https://kodeverk.dev.adeo.no
  SECURITY_TOKEN_SERVICE_TOKEN_URL: https://security-token-service.nais.preprod.local/rest/v1/sts/token
  INNTEKTSKOMPONENT_BASE_URL: https://app-q1.adeo.no/inntektskomponenten-ws/rs
