app: flex-fss-proxy
namespace: flex
team: flex
azureTenant: nav.no
environment: prod
ingress: https://flex-fss-proxy.prod-fss-pub.nais.io
env:
  MODIACONTEXTHOLDER_URL: https://modiacontextholder.intern.nav.no
  KODEVERK_URL: https://kodeverk.nais.adeo.no
