apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: {{app}}
  namespace: {{namespace}}
  labels:
    team: {{team}}
spec:
  image: {{image}}
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 90
  port: 8080
  ingresses:
    - {{ingress}}
  liveness:
    path: /internal/isAlive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /internal/isReady
    initialDelay: 10
    periodSeconds: 5
    timeout: 5
  resources:
    limits:
      cpu: 500m
      memory: 500Mi
    requests:
      cpu: 200m
      memory: 100Mi
  accessPolicy:
    inbound:
      rules:
        - application: sykepengesoknad-korrigering-metrikk
          namespace: flex
          cluster: {{environment}}-gcp
        - application: sykepengesoknad-narmesteleder-varsler
          namespace: flex
          cluster: {{environment}}-gcp
        - application: spinnsyn-frontend-interne
          namespace: flex
          cluster: {{environment}}-gcp
        - application: flex-joark-mottak
          namespace: flex
          cluster: {{environment}}-gcp
  azure:
    application:
      enabled: true
      tenant: {{azureTenant}}
  envFrom:
    - secret: flex-fss-proxy-serviceuser
  env:
  {{#each env}}
     - name: {{@key}}
       value: {{this}}
  {{/each}}
